services:
  app:
    container_name: enviloup-main-page
    image: enviloup/main-page:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "127.0.0.1:${SOME_VALUE:-8081}:80"
